homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  external_url: !secret external_url
  internal_url: "http://hassio.local:8123"

  unit_system: metric

  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Kiev

  customize: !include customize.yaml

http:
#  api_password: !secret api_password
  use_x_forwarded_for: True
  trusted_proxies: 10.20.30.1
  ip_ban_enabled: True
  login_attempts_threshold: 10

#  base_url: hass.kaspian.info
#  cors_allowed_origins: https://hass.kaspian.info

# Enables the frontend
frontend:

# View all events in a logbook
logbook:

# Allows you to issue voice commands from the frontend
conversation:

# Discover some devices automatically
discovery:

# Track the sun
sun:

# Enables support for tracking state changes over time.
history:

# Show links to resources in log and frontend
# introduction:

system_health:

#mqtt:
#  broker: mqtt.lan
#  port: 1883
mqtt: !include mqtt/mqtt.yaml
    
recorder: !include recorder.yaml
group: !include_dir_merge_named groups

#media_player: !include_dir_merge_list media_players

automation: !include_dir_merge_list automations

telegram_bot:
  - platform: broadcast
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_alex_id
      - !secret telegram_vika_id
      - !secret telegram_kostya_id

notify: !include_dir_merge_list notifies

logger:
  default: debug
