# Outdated version of firmware, includes different payload

- platform: mqtt
  name: "0cd35aef_switch"
  command_topic: "devices/0cd35aef/switch/on/set"
  state_topic: "devices/0cd35aef/switch/on"
  retain: true
  payload_on: "true"
  payload_off: "false"
