automations:
    name: "Automations"
    entities:
      - automation.day_time__turn_water_heater_on
      - automation.day_time__turn_water_heater_off
      - automation.night_time__turn_water_heater_on
      - automation.night_time__turn_water_heater_off
