- platform: mqtt
  name: "cf7911e0_Temperature"
  state_topic: "devices/cf7911e0/sensor/temperature"
  qos: 0
  unit_of_measurement: "ºC"

- platform: mqtt
  name: "cf7911e0_Humidity"
  state_topic: "devices/cf7911e0/sensor/humidity"
  qos: 0
  unit_of_measurement: "%"
