- platform: mqtt
  name: "0x00158d000273597f_door_sensor"
  payload_on: false
  payload_off: true
  state_topic: "zigbee2mqtt/0x00158d000273597f"
  value_template: '{{ value_json.contact }}'
  device_class: "door"
