- alias: 'Aquarium. Light-ON'
  trigger:
      platform: time
      at: '10:00:00'
  action:
    service: switch.turn_on
    entity_id: switch.0cd35aef_switch

- alias: 'Aquarium. Light-OFF'
  trigger:
      platform: time
      at: '22:00:00'
  action:
    service: switch.turn_off
    entity_id: switch.0cd35aef_switch
