- alias: 'Door open notifier'
  trigger:
    platform: state
    entity_id: binary_sensor.0x00158d000273597f_door_sensor
    from: 'off'
    to: 'on'
  action:
    - service: notify.notify_alex
      data:
        title: "Двері відчинені"
        message: "Вхідні двері відчинені"
    - service: notify.notify_vika
      data:
        title: "Двері відчинені"
        message: "Вхідні двері відчинені"
    - service: notify.notify_kostya
      data:
        title: "Двері відчинені"
        message: "Вхідні двері відчинені"

